CREATE TABLE IF NOT EXISTS odoo_orders_summary (
  order_key VARCHAR(120) NOT NULL,
  line_account_id INT NOT NULL DEFAULT 0,
  odoo_order_id INT DEFAULT NULL,
  customer_id VARCHAR(64) DEFAULT NULL,
  partner_id VARCHAR(64) DEFAULT NULL,
  customer_name VARCHAR(255) DEFAULT NULL,
  customer_ref VARCHAR(120) DEFAULT NULL,
  salesperson_id VARCHAR(64) DEFAULT NULL,
  salesperson_name VARCHAR(255) DEFAULT NULL,
  amount_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  amount_tax DECIMAL(14,2) NOT NULL DEFAULT 0,
  amount_untaxed DECIMAL(14,2) NOT NULL DEFAULT 0,
  currency VARCHAR(16) DEFAULT 'THB',
  state VARCHAR(64) DEFAULT NULL,
  state_display VARCHAR(128) DEFAULT NULL,
  invoice_status VARCHAR(64) DEFAULT NULL,
  payment_status VARCHAR(64) DEFAULT NULL,
  delivery_type VARCHAR(64) DEFAULT NULL,
  line_user_id VARCHAR(100) DEFAULT NULL,
  first_event_at DATETIME DEFAULT NULL,
  last_event_at DATETIME DEFAULT NULL,
  created_at_odoo DATETIME DEFAULT NULL,
  date_order DATE DEFAULT NULL,
  expected_delivery_date DATE DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  synced_at DATETIME DEFAULT NULL,
  PRIMARY KEY (order_key, line_account_id),
  KEY idx_orders_summary_line_account_last_event (line_account_id, last_event_at),
  KEY idx_orders_summary_partner (partner_id),
  KEY idx_orders_summary_customer_ref (customer_ref),
  KEY idx_orders_summary_odoo_order_id (odoo_order_id),
  KEY idx_orders_summary_date_order (date_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS odoo_customers_cache (
  customer_id VARCHAR(64) NOT NULL,
  line_account_id INT NOT NULL DEFAULT 0,
  partner_id VARCHAR(64) DEFAULT NULL,
  customer_name VARCHAR(255) DEFAULT NULL,
  customer_ref VARCHAR(120) DEFAULT NULL,
  phone VARCHAR(64) DEFAULT NULL,
  email VARCHAR(191) DEFAULT NULL,
  city VARCHAR(120) DEFAULT NULL,
  state VARCHAR(120) DEFAULT NULL,
  line_user_id VARCHAR(100) DEFAULT NULL,
  line_display_name VARCHAR(255) DEFAULT NULL,
  salesperson_id VARCHAR(64) DEFAULT NULL,
  salesperson_name VARCHAR(255) DEFAULT NULL,
  credit_limit DECIMAL(14,2) NOT NULL DEFAULT 0,
  total_due DECIMAL(14,2) NOT NULL DEFAULT 0,
  overdue_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  trust_level VARCHAR(64) DEFAULT NULL,
  orders_count_total INT NOT NULL DEFAULT 0,
  orders_count_30d INT NOT NULL DEFAULT 0,
  spend_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  spend_30d DECIMAL(14,2) NOT NULL DEFAULT 0,
  first_order_at DATETIME DEFAULT NULL,
  latest_order_at DATETIME DEFAULT NULL,
  last_invoice_at DATETIME DEFAULT NULL,
  last_payment_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  synced_at DATETIME DEFAULT NULL,
  PRIMARY KEY (customer_id, line_account_id),
  KEY idx_customers_cache_partner (partner_id),
  KEY idx_customers_cache_ref (customer_ref),
  KEY idx_customers_cache_latest_order (latest_order_at),
  KEY idx_customers_cache_due (overdue_amount, total_due),
  KEY idx_customers_cache_line_user (line_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS odoo_invoices_cache (
  invoice_number VARCHAR(120) NOT NULL,
  line_account_id INT NOT NULL DEFAULT 0,
  invoice_id INT DEFAULT NULL,
  order_key VARCHAR(120) DEFAULT NULL,
  customer_id VARCHAR(64) DEFAULT NULL,
  partner_id VARCHAR(64) DEFAULT NULL,
  customer_name VARCHAR(255) DEFAULT NULL,
  amount_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  amount_residual DECIMAL(14,2) NOT NULL DEFAULT 0,
  amount_paid DECIMAL(14,2) NOT NULL DEFAULT 0,
  state VARCHAR(64) DEFAULT NULL,
  payment_state VARCHAR(64) DEFAULT NULL,
  invoice_date DATE DEFAULT NULL,
  due_date DATE DEFAULT NULL,
  is_overdue TINYINT(1) NOT NULL DEFAULT 0,
  days_overdue INT NOT NULL DEFAULT 0,
  line_user_id VARCHAR(100) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  synced_at DATETIME DEFAULT NULL,
  PRIMARY KEY (invoice_number, line_account_id),
  KEY idx_invoices_cache_partner (partner_id),
  KEY idx_invoices_cache_customer (customer_id),
  KEY idx_invoices_cache_due (is_overdue, due_date),
  KEY idx_invoices_cache_order_key (order_key),
  KEY idx_invoices_cache_invoice_id (invoice_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS odoo_slips_cache (
  slip_id INT NOT NULL,
  line_account_id INT NOT NULL DEFAULT 0,
  line_user_id VARCHAR(100) DEFAULT NULL,
  customer_name VARCHAR(255) DEFAULT NULL,
  order_key VARCHAR(120) DEFAULT NULL,
  order_id INT DEFAULT NULL,
  invoice_id INT DEFAULT NULL,
  bdo_id INT DEFAULT NULL,
  odoo_slip_id INT DEFAULT NULL,
  slip_inbox_id INT DEFAULT NULL,
  amount DECIMAL(14,2) DEFAULT NULL,
  matched_amount DECIMAL(14,2) DEFAULT NULL,
  payment_date DATE DEFAULT NULL,
  payment_method VARCHAR(64) DEFAULT NULL,
  status VARCHAR(32) DEFAULT NULL,
  confidence VARCHAR(64) DEFAULT NULL,
  match_reason TEXT DEFAULT NULL,
  matched_at DATETIME DEFAULT NULL,
  matched_by VARCHAR(100) DEFAULT NULL,
  uploaded_by VARCHAR(100) DEFAULT NULL,
  image_path TEXT DEFAULT NULL,
  image_url TEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  synced_at DATETIME DEFAULT NULL,
  PRIMARY KEY (slip_id),
  KEY idx_slips_cache_line_account_status (line_account_id, status),
  KEY idx_slips_cache_payment_date (payment_date),
  KEY idx_slips_cache_bdo_id (bdo_id),
  KEY idx_slips_cache_order_key (order_key),
  KEY idx_slips_cache_slip_inbox_id (slip_inbox_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS odoo_order_events (
  webhook_log_id INT NOT NULL,
  order_key VARCHAR(120) NOT NULL,
  event_type VARCHAR(120) NOT NULL,
  event_category VARCHAR(64) DEFAULT NULL,
  status VARCHAR(32) DEFAULT NULL,
  old_state VARCHAR(64) DEFAULT NULL,
  new_state VARCHAR(64) DEFAULT NULL,
  payload_summary JSON DEFAULT NULL,
  line_account_id INT NOT NULL DEFAULT 0,
  processed_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (webhook_log_id),
  KEY idx_order_events_order_key_processed (order_key, processed_at),
  KEY idx_order_events_line_account (line_account_id),
  KEY idx_order_events_event_type (event_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS odoo_dashboard_cache_meta (
  cache_key VARCHAR(120) NOT NULL,
  cache_type VARCHAR(64) NOT NULL,
  last_synced_at DATETIME DEFAULT NULL,
  is_dirty TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (cache_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS odoo_sync_log (
  id INT NOT NULL AUTO_INCREMENT,
  job_type VARCHAR(32) NOT NULL,
  started_at DATETIME NOT NULL,
  completed_at DATETIME DEFAULT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'running',
  triggered_by VARCHAR(32) DEFAULT NULL,
  line_account_id INT DEFAULT NULL,
  records_processed INT NOT NULL DEFAULT 0,
  records_inserted INT NOT NULL DEFAULT 0,
  records_updated INT NOT NULL DEFAULT 0,
  execution_duration_ms INT DEFAULT NULL,
  error_message TEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_sync_log_status_started (status, started_at),
  KEY idx_sync_log_line_account (line_account_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
